x1 = int(input("Введите координату x1: "))
y1 = int(input("Введите координату y1: "))
x2 = int(input("Введите координату x2: "))
y2 = int(input("Введите координату y2: "))
lx = abs(x1 - x2)
ly = abs(y1 - y2)
s = round(((lx ** 2) + (ly ** 2)) ** 0.5, 2)
print("Расстояние =", s)
