side1 = int(input("Введите сторону квадрата 1: "))
side2 = int(input("Введите сторону квадрата 2: "))
p = (side1 * 2) + (side2 * 2)
d = round(((side1 ** 2) + (side2 ** 2)) ** 0.5, 2)
print("Периметр = ", p)
print("Диагональ = ", d)
